name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Force -Scope CurrentUser Pester -MaximumVersion '5.99.99'
          Set-Location .scripts
          dotnet publish -o ..
        shell: pwsh

      - name: Run tests and generate coverage report
        env:
          include_integration_tests: true
        run: |
          $res = Invoke-Pester -CI -PassThru
          if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
          }
        shell: pwsh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          use_oidc: true
