name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.0.0

      - name: Install dependencies
        run: |
          Install-Module -Force -Scope CurrentUser Pester -MaximumVersion '5.99.99'
          cd .scripts
          dotnet publish -o ..
        shell: pwsh

      - name: Run tests and generate coverage report
        env:
          include_integration_tests: true
        run: |
          $res = Invoke-Pester -CI -PassThru
          if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
          }
        shell: pwsh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
