name: Docs Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          cd .scripts
          dotnet publish -o ..

      - name: Check that documentation was regenerated if needed
        run: |
          .scripts/Generate-Documentation.ps1
          git diff --exit-code .docs/reference.md
        shell: pwsh
