name: Docs Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        shell: pwsh
        run: |
          Set-Location .scripts
          dotnet publish -o ..

      - name: Check that documentation was regenerated if needed
        run: |
          .\.scripts\Generate-Documentation.ps1
          git diff --exit-code .docs/reference.md
        shell: pwsh
