name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Force -Scope CurrentUser Pester -MaximumVersion '5.99.99'
          Set-Location .scripts
          dotnet publish -o ..
        shell: pwsh

      - name: Run tests and generate coverage report
        env:
          include_integration_tests: true
        run: |
          $res = Invoke-Pester -PassThru -CodeCoverage nvm.psm1;
          if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
          }
        shell: pwsh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true

      - name: Prepare Artifacts
        shell: pwsh
        run: |
          New-Item -Path nvm -ItemType Directory -Force | Out-Null
          Copy-Item nvm.* nvm
          Copy-Item SemVer.dll nvm
          Copy-Item *.md nvm
          Copy-Item autocomplete-utils.ps1 nvm
          Compress-Archive -Path nvm\* -DestinationPath nvm\nvm.zip -Force

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: nvm
          path: ./nvm

  release_gallery:
    name: Release to PowerShell Gallery
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: nvm
          path: nvm

      - name: Publish to PowerShell Gallery
        env:
          POWERSHELL_GALLERY: ${{ secrets.POWERSHELL_GALLERY }}
        run: |
          Publish-Module -Path (Get-Location) -NuGetApiKey $env:POWERSHELL_GALLERY -Force
        working-directory: nvm
        shell: pwsh

  release_github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: nvm
          path: nvm

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
        run: |
          gh release create "${{ github.ref_name }}" .\nvm\nvm.zip `
            --repo "${{ github.repository }}" `
            --title "Release ${{ github.ref_name }}" `
            --notes "Latest release of PowerShell nvm"
